In [1]:
# # [ ['Wales', 'Scotland', 'Friendly', 'Wales'] ] -> output should be LOSS
from sklearn import tree
import csv
import numpy as np

data = [] #to store the data(without the column that contains the class) after reading
target = [] # contains the class column
featureName = [] # the name of the columns, to use in different situations
targetName = [] # the unique values of classlabels
className = [] # name of the class


In [2]:
def readData( ):
    
    FILENAME = "soccer.csv"
    COLUMNSTOIGNORE = [0,3,4,6]  # ignoring the useless columns, these columns will not be read
    NULLVALUEINDICATOR = [ -100000, "?"]
    
    global data, target, featureName, targetName, className
    tx = []
    ty = []
    labels = []
    columnName = []
    with open(FILENAME,encoding="utf8") as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        for i, rows in enumerate(csv_reader):
#             if(i>5000):
#                 break #breaking early just for quick runs
            tempData = []
            for j,data in enumerate(rows): #reading every column info from a row and ignoring the unnecessary columns
                if j not in COLUMNSTOIGNORE:
                    tempData.append(data)
            nullvalueFound = 0
            for j in NULLVALUEINDICATOR:
                if(j in tempData):
                    nullvalueFound = 1
                    break
            if(nullvalueFound):
                continue
            if i>0: #0 th row should be the name row
                datas = tempData[:-1]  #last column is the label column so seperating those
                label = (tempData[-1:]) #taking just he labels
                #print(datas, label)
                tx.append(datas)
                ty.append(label)
            else:
                columnName.extend(tempData) #copying array
    data = tx
    target = ty
    targetName = np.unique(target).tolist()
    featureName = columnName[:-1]
    className = columnName[-1:]
    print(className)

In [3]:
readData()

# print("Data In Order: ")
# print("Target names: ")
# print(targetName)
# print("Features")
# print(featureName)
# print("Data")
# print(data)
# print("Targets")
# print(target)

['home_team_result']


In [4]:
# changing categorical data to one hot
'''
Training the encoder here on all the data read from the file because 
if we train the encoder from only the traning dataset then when testing,
the encoder thus the model might face unknown valus that don't have any 
one hot value.
Like in testingdata there might be a column named Ghana but there is no
value named Ghana in training dataset. so the encoder/model won't know any value for Ghana
'''
from sklearn import preprocessing

dataEncoder = preprocessing.OneHotEncoder()
dataEncoder.fit(data)  #training the encoder

targetEncoder = preprocessing.OneHotEncoder()
targetEncoder.fit(target)

# print(dataEncoder.categories_[])
#generating combined feature name from the one hot conversion

# onehotFeatureNames = []
# for i, val in enumerate(dataEncoder.categories_):
# #     print(featureName[i])
#     for j in val:
#         onehotFeatureNames.append("{}:{}".format(featureName[i],j))
# print(onehotFeatureNames)

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [5]:
# seperating training data and testing data
# for training we use the variables data, target

from sklearn.utils import shuffle
import math

SPLIT = 70 # means: out of 100, 70 will go to training and 30 will go to testing

data, target = shuffle(np.array(data), np.array(target))

splitPoint = math.ceil( len(data)*SPLIT / 100.0 )
testingData = data[splitPoint:]
testingTarget = target[splitPoint:]
data = data[:splitPoint]
target = target[:splitPoint]

print("Training Data Size: ", len(data),"Testing Data Size: ", len(testingData))
# print(testingData, testingTarget)

Training Data Size:  27080 Testing Data Size:  11605


In [6]:
#converting the data using the previously trained encoder
oneHotData = dataEncoder.transform(data) #converting the data

oneHotTarget = targetEncoder.transform(target)

# print(encData.toarray())
# print(enc.categories_)
# print(eTarget.categories_)


In [7]:
spTarget = []
for i in target:
    spTarget.append(i[0])
# print(spTarget)

In [8]:

#support vector machine

from sklearn  import svm
SVM = svm.SVC(gamma='scale', decision_function_shape='ovo')

SVM.fit(oneHotData.toarray(), spTarget)

print(SVM.support_vectors_)
print(SVM.support_ )
print(SVM.n_support_ )


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[    4     5     7 ... 27073 27074 27075]
[ 6282  7150 10067]


In [9]:

# ['Wales', 'Scotland', 'Friendly', 'Wales']
trialData = [ ['Wales', 'Scotland', 'Friendly', 'Wales'] ]
print("Input: ",trialData)
trialData = dataEncoder.transform( trialData )  # transforming the given data in to our own one hot
prediction = SVM.predict(trialData.toarray())
predictionResult = targetEncoder.inverse_transform(prediction)
print("Prediction: ", predictionResult[0][0])

Input:  [['Wales', 'Scotland', 'Friendly', 'Wales']]


ValueError: Expected 2D array, got 1D array instead:
array=['Loss'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
# ERROR CALCULATION

correctAnswer = 0
# print(testingData)
testData = dataEncoder.transform( testingData )
prediction = SVM.predict(testData.toarray())
predictionResult = targetEncoder.inverse_transform(prediction)

for i,val in enumerate(predictionResult):
    if(testingTarget[i] == predictionResult[i]):
        correctAnswer +=1
successRate = correctAnswer / len(testingTarget)
print("Success rate: {}%".format(successRate*100))